version: "0.1"

services:
  zyrasync:
    container_name: zyrasync-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
        SERVER_HOST: 0.0.0.0
        SERVER_PORT: 5555
    command: python3 runserver.py


